# Generated by Django 2.0.10 on 2019-09-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190929_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default="2018-12-3"),
            preserve_default=False,
        ),
    ]
