# Generated by Django 2.0.10 on 2019-09-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
    ]
