# Generated by Django 2.0.10 on 2019-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191001_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Kuca'), (2, 'Zgrada'), (3, 'Hotel'), (4, 'Restoran')], default=1),
        ),
    ]
