# Generated by Django 2.0.10 on 2019-10-09 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191003_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z ]+$', 'Only letters and spaces are allowed in the Location Name.')]),
        ),
    ]
