# Generated by Django 2.2.5 on 2019-12-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191009_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
